[build]
  # 'client' फोल्डरमध्ये जाऊन बिल्ड करा
  command = "cd client && npm install && npm run build"
  
  # CRA मध्ये तयार होणारे फोल्डर 'build' असते (dist नाही)
  publish = "client/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200