"""add review_notes to claims

Revision ID: 9f295b5d1dc5
Revises: e7cc241afe52
Create Date: 2026-04-03 00:15:15.343732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f295b5d1dc5'
down_revision: Union[str, Sequence[str], None] = 'e7cc241afe52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('review_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'review_notes')
    # ### end Alembic commands ###
