"""added date_of_birth to users

Revision ID: b83263ab65c0
Revises: d4b8e6f1a2c3
Create Date: 2026-03-31 16:25:23.498278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83263ab65c0'
down_revision: Union[str, Sequence[str], None] = 'd4b8e6f1a2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_policy_documents_id'), 'policy_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_documents_id'), table_name='policy_documents')
    # ### end Alembic commands ###
